version: '3'
services:
  # mmq-db:
  #   image: mongo:4.2.1-bionic
  #   ports:
  #   - "27017:27017"
  #   volumes:
  #   - mongodata:/data/db
  mmq-service:
    build: ./service
    ports:
    - "9000:9000"
    environment:
    - ASPNETCORE_ENVIRONMENT=Docker  # probably not needed
    - ASPNETCORE_URLS=http://0.0.0.0:9000  # probably not needed
    volumes:
    - fasterdbo:/opt/faster
    # shm_size: "2gb"
    links:
    - "mmq-db"
  mmq-benchmark-console:
    build:
      context: ./service/
      dockerfile: ./MinMQ.BenchmarkConsole/Dockerfile
    links:
    - "mmq-service"
  mmq-service-express:
    build: ./benchmark/service-express
    ports:
    - "4000:4000"
  mmq-service-hapi:
    build: ./benchmark/service-hapi
    ports:
    - "1000:1000"
  mmq-service-nodejs:
    build: ./benchmark/service-nodejs
    # links:
    # - "mmq-db:database"
    ports:
    - "8000:8000"
  mmq-benchmarks:
    build: ./benchmark
    links:
    - "mmq-service"
    - "mmq-service-nodejs"
    - "mmq-service-express"
  mmq-db:
    # https://docs.docker.com/compose/environment-variables/
    # https://hub.docker.com/_/postgres
    image: postgres:12.1
    restart: always
    ports:
    - "5432:5432"
    volumes:
    - postgresdata:/var/lib/postgresql/data
    env_file:
    - .env
    environment:
      # - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_DB=mmq
volumes:
  # mongodata: {}
  fasterdbo:
    # DOESN'T WORK FROM INSIDE DOCKER-COMPOSE TO ALLOCATE BIG VOLUME
    # driver: local
    # driver_opts:
      # type: 
      # o: size=1200m
      # device: K://docker-faster-hlog
    external: true
  postgresdata: {}
  