version: '3'
services:
  # mmq-db:
  #   image: mongo:4.2.1-bionic
  #   ports:
  #   - "27017:27017"
  #   volumes:
  #   - mongodata:/data/db
  mmq-service-kestrel:
    build: ./service-kestrel
    ports:
    - "9000:9000"
    environment:
    - ASPNETCORE_ENVIRONMENT=Docker
    - ASPNETCORE_URLS=http://0.0.0.0:9000
    volumes:
    - fasterdata:/opt/faster
    shm_size: "2gb"
  mmq-service-express:
    build: ./benchmark/service-express
    ports:
    - "4000:4000"
  mmq-service-nodejs:
    build: ./benchmark/service-nodejs
    # links:
    # - "mmq-db:database"
    ports:
    - "8000:8000"
  mmq-load-tests:
    build: ./benchmark
    links:
    - "mmq-service-kestrel"
    - "mmq-service-nodejs"
    - "mmq-service-express"
volumes:
  mongodata: {}
  fasterdata:
    # DOESN'T WORK FROM INSIDE DOCKER-COMPOSE TO ALLOCATE BIG VOLUME
    # driver: local
    # driver_opts:
      # type: 
      # o: size=1200m
      # device: K://docker-faster-hlog
    external: true